//
//  MACSHA256Tests.swift
//  S3FileUploadSignv4iOSTests
//
//  Created by Avadesh Kumar on 11/10/18.
//  Copyright © 2018 Avadesh Kumar. All rights reserved.
//

import XCTest
@testable import S3FileUploadSignv4iOS

//Input and expected output values are taken from amazon link: https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html#signature-v4-examples-other
class MACSHA256Tests: XCTestCase {
    
    let key = "AWS4wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY"
    let dateString = "20120215"
    let regionName = "us-east-1"
    let serviceName = "iam"
    let requestName = "aws4_request"
   
    let expectedKeyHex: String = "969fbb94feb542b71ede6f87fe4d5fa29c789342b0f407474670f0c2489e0a0d"
    let expectedDateRegionKey = "69daa0209cd9c5ff5c8ced464a696fd4252e981430b10e3d3fd8e2f197d7a70c"
    let expectedDateRegionServiceKey = "f72cfd46f26bc4643f06a11eabb6c0ba18780c19a8da0c31ace671265e3c87fa"
    let expectedDateRegionServiceRequestKey = "f4780e2d9f65fa895f9c67b32ce1baf0b0d8a43505a000a1a9e090d414db404d"
    let expectedKeyHashString = "41575334774a616c725855746e46454d492f4b374d44454e472b62507852666943594558414d504c454b4559"

    var keyData: Data!

    override func setUp() {
        super.setUp()
        keyData = key.utf8Data()
    }
    
    func testSHA256Initialization() {
        
        let hmac = HMACSHA256(using: keyData)
        XCTAssertNotNil( hmac, "HMacSHA256 initialization issue")
    }
    
    func testDateSHA256Generation() {
        
        let dateKey:[UInt8] = HMACSHA256(using: keyData).generateSHA256(with: dateString.bytesArray())

        XCTAssertEqual(dateKey.hexString(), expectedKeyHex, "Wrong date hash generated by HMacSHA256")
    }
    
    func testMultiLevelSHA256Generation() {
        
        let dateKey:[UInt8] = HMACSHA256(using: keyData).generateSHA256(with: dateString.bytesArray())
        let dateRegionKey: [UInt8] = HMACSHA256(using: Data(dateKey)).generateSHA256(with: regionName.bytesArray())
        let dateRegionServiceKey: [UInt8] = HMACSHA256(using: Data(dateRegionKey)).generateSHA256(with: serviceName.bytesArray())
        let dateRegionServiceRequestKey: [UInt8] = HMACSHA256(using: Data(dateRegionServiceKey)).generateSHA256(with: requestName.bytesArray())

        XCTAssertEqual(dateKey.hexString(), expectedKeyHex, "Wrong date hash generated by HMacSHA256")
        XCTAssertEqual(dateRegionKey.hexString(), expectedDateRegionKey, "Wrong date + region hash generated by HMacSHA256")
        XCTAssertEqual(dateRegionServiceKey.hexString(), expectedDateRegionServiceKey, "Wrong date + Region + Service hash generated by HMacSHA256")
        XCTAssertEqual(dateRegionServiceRequestKey.hexString(), expectedDateRegionServiceRequestKey, "Wrong date + Region + Service + request hash generated by HMacSHA256")
        
    }
    
    func testHexStringGeneration() {
        
        let hexString = keyData.hexString()
        XCTAssertEqual(hexString, expectedKeyHashString, "Wrong hex string generation")
    }
}
